--repository ppa:graphics-drivers/ppa
--package "thermald tlp tlp-rdw powertop va-driver-all vainfo libva2 nvidia-driver-396 nvidia-prime bbswitch-dkms pciutils gstreamer1.0-libav gstreamer1.0-vaapi vlc "
--file /home/matteo/dell-xps-9570-ubuntu-respin/wrapper-network.sh
--file /home/matteo/dell-xps-9570-ubuntu-respin/wrapper-nvidia.sh
--file /home/matteo/dell-xps-9570-ubuntu-respin/wrapper-powertop.sh
--file /home/matteo/dell-xps-9570-ubuntu-respin/services/gpuoff.service
--file /home/matteo/dell-xps-9570-ubuntu-respin/services/powertop.service
--command wrapper-network.sh
--command wrapper-nvidia.sh
--command wrapper-powertop.sh
--grub "quiet acpi_rev_override=1 acpi_osi=Linux scsi_mod.use_blk_mq=1 nouveau.modeset=0 nouveau.runpm=0"
